# Generated by Django 3.1.7 on 2021-08-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_friend_first', to=settings.AUTH_USER_MODEL)),
                ('Friend_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendship_friend_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendrequests_friend_receiver', to=settings.AUTH_USER_MODEL)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests_friend_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
