# Generated by Django 4.0.2 on 2022-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apigroupmembers',
            name='id',
        ),
        migrations.AddField(
            model_name='apigroup',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apigroupmembers',
            name='GroupId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
