# Generated by Django 4.0.2 on 2022-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimessage',
            name='Receiver',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apimessage',
            name='Sender',
            field=models.CharField(max_length=200),
        ),
    ]
