# Generated by Django 4.0.2 on 2022-04-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0002_alter_apicomplain_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.apipost')),
                ('LikerPid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=1024)),
                ('Time', models.DateTimeField()),
                ('LikedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.apipost')),
                ('LikerPid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
