# Generated by Django 4.0.2 on 2022-04-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_apilikes_apicomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicomments',
            old_name='LikerPid',
            new_name='CommentorId',
        ),
        migrations.RenameField(
            model_name='apicomments',
            old_name='LikedPostId',
            new_name='PostId',
        ),
        migrations.RenameField(
            model_name='apilikes',
            old_name='LikerPid',
            new_name='LikerId',
        ),
    ]
